// Generated by CoffeeScript 2.3.2
module.exports = {
  default: {
    db_url: "mongodb://127.0.0.1:27017",
    redis: {
      host: '127.0.0.1',
      port: 7777
    },
    email: {
      email: 'service@comunion.io',
      mailHost: 'smtp.exmail.qq.com',
      mailPsd: 'RjZoofwvjpamFk89',
      name: 'Comunion Website'
    }
  }
};

//	production:
//		db_port: 27017
