// Generated by CoffeeScript 2.3.2
module.exports = function(req, bo) {
  if (_cache.get(bo._cap).substr(0, 4) === bo._captcha) {
    return null;
  }
  return {
    msg: '验证码错误!',
    error: true
  };
};
