// Generated by CoffeeScript 2.3.2
(function() {
  var Web3;

  Web3 = require('web3');

  module.exports = {
    web3: function() {
      var web3;
      return web3 = new Web3(new Web3.providers.HttpProvider(setting.web3Address));
    },
    getContract: function(abiFile, addr) {
      var abi;
      abi = JSON.parse(fs.readFileSync(abiFile));
      return new web3.eth.Contract(abi, addr);
    },
    send: function(abiFile, addr, acct, data) {
      return this.getContract(abiFile, addr).sendCoin.sendTransaction(acct, 1, data);
    },
    trans: async function(from, data) {
      var rec;
      rec = (await this.web3().eth.sendTransaction({from, data}).once('receipt', function(rec) {}).once('confirmation', function(cfn, rec) {}).on('err', function(err) {
        return log(err);
      }));
      return log(rec);
    },
    checkTran: async function(hash) {
      var e;
      try {
        return (await this.web3().eth.getTransactionReceipt(hash));
      } catch (error) {
        e = error;
        return log(e);
      }
    }
  };

}).call(this);
