// Generated by CoffeeScript 2.3.2
module.exports = function(code, name) {
  this.db = _db[code].collection(name || 'b_cache');
  this.db.createIndex({
    t: 1
  }, {
    expireAfterSeconds: 0
  });
  this.set = function(k, v, t = 7200) {
    var $set;
    $set = {
      v: v,
      t: new Date(Date.now() + t * 1000)
    };
    return this.db.findOneAndUpdate({k}, {$set}, {
      upsert: true
    });
  };
  this.get = function(k) {
    return this.db.findOne({k}).then(function(ret) {
      if (ret) {
        return ret.v;
      } else {
        return null;
      }
    });
  };
  this.del = function(k) {
    return this.db.findOneAndDelete({k});
  };
  this.update = function(k, $set) {
    return this.db.findOneAndUpdate({k}, {$set});
  };
  return this;
};
