// Generated by CoffeeScript 2.3.2
module.exports = async function(code, entity, d) {
  var q;
  if (d.id) {
    await dao.delItem(code, entity, {
      _id: oid(d.id)
    });
    if (entity === 'user') {
      await dao.delItem(code, 'membership', {
        uid: oid(d.id)
      });
    }
    return {
      msg: 'm_del_ok'
    };
  } else if (d.body && d.body.q) {
    q = queryUtil.queryClean(d.body.q);
    await dao.remove(code, entity, q);
    return {
      msg: 'm_del_ok'
    };
  }
};
