// Generated by CoffeeScript 2.3.2
(function() {
  var find;

  find = require('../service/dao/find');

  module.exports = {
    get: async function(req, rsp) {
      var res, user;
      req.id = req.params.id;
      req.params.entity = 'record';
      res = (await find(req.c.code, req.params.entity, req));
      if (!res.entity) {
        rsp.status(350);
      }
      user = (await dao.get(db, "user", {
        "wallet.address": res.entity.receiver
      }));
      res.entity.receiveUser = user;
      return rsp.send(res);
    },
    list: async function(req, rsp) {
      var k, ref, res, user, v;
      req.params.entity = 'record';
      res = (await find(req.c.code, req.params.entity, req));
      ref = res.entities;
      for (k in ref) {
        v = ref[k];
        user = (await dao.get(db, "user", {
          "wallet.address": v.receiver
        }));
        v.receiveUser = user;
      }
      return rsp.send(res);
    }
  };

}).call(this);
