// Generated by CoffeeScript 2.3.2
(function() {
  var web3;

  web3 = require('../service/web3');

  module.exports = {
    receipt: async function(req, rsp) {
      var code, e, receipt, tx;
      code = req.c.code;
      try {
        tx = (await dao.one(code, 'tx', {
          txHash: req.params.hash
        }));
        if ((tx != null) && tx.status === 2) {
          receipt = (await web3.checkTran(tx.txHash));
          if (receipt && (receipt.status != null)) {
            if (receipt.status === '0x1') {
              tx.status = 1;
            } else {
              tx.status = 0;
            }
            await dao.findAndUpdatedb("tx", {
              txHash: tx.txHash
            }, {
              $set: {
                status: tx.status
              }
            });
          }
        }
        if (tx != null) {
          return rsp.send(tx);
        } else {
          return rsp.send({
            err: -1,
            msg: '数据错误'
          });
        }
      } catch (error) {
        e = error;
        log(e);
        return rsp.send({
          err: -1,
          msg: '数据错误'
        });
      }
    }
  };

}).call(this);
