// Generated by CoffeeScript 2.3.2
(function() {
  var web3;

  web3 = require('../service/web3');

  module.exports = {
    receipt: async function(req, rsp) {
      var code, e, receipt, tx;
      code = req.c.code;
      try {
        tx = (await dao.one(code, 'tx', {
          _id: oid(req.params.id)
        }));
        if (tx.status != null) {
          receipt = (await web3.checkTran(tx.txhash));
          if (receipt && receipt.status) {
            if (receipt.status === '0x1') {
              tx.status = 1;
            } else {
              tx.status = 0;
            }
            await dao.findAndUpdatedb("tx", {
              txhash: tx.txhash
            }, {
              $set: {
                status: tx.status
              }
            });
          }
        }
        return rsp.send({
          tx: tx
        });
      } catch (error) {
        e = error;
        log(e);
        return rsp.send({
          err: 1,
          msg: '数据错误'
        });
      }
    }
  };

}).call(this);
