// Generated by CoffeeScript 2.3.2
(function() {
  var aws, bk, multer, multerS3, s3, spacesEndpoint, upload;

  aws = require('aws-sdk');

  multer = require('multer');

  multerS3 = require('multer-s3');

  spacesEndpoint = new aws.Endpoint('sgp1.digitaloceanspaces.com');

  aws.config.loadFromPath('controller/creds.json');

  s3 = new aws.S3({
    endpoint: spacesEndpoint
  });

  bk = 'comunion-avatar';

  upload = multer({
    storage: multerS3({
      s3: s3,
      bucket: bk,
      acl: 'public-read',
      key: function(req, file, cb) {
        req.fk = 'avatar_' + util.randomChar(9) + '.' + file.originalname.split('.')[1];
        return cb(null, req.fk);
      }
    })
  }).array('upload', 1);

  app.post('/a/upload', function(req, rsp) {
    return upload(req, rsp, function(error) {
      if (error) {
        log(error);
        return rsp.json({
          err: 1,
          msg: 'upload err'
        });
      } else {
        log('File uploaded successfully.');
        log(`http://${bk}.sgp1.digitaloceanspaces.com/${req.fk}`);
        return rsp.json({
          msg: 'upload successfully',
          url: `http://${bk}.sgp1.digitaloceanspaces.com/${req.fk}`
        });
      }
    });
  });

}).call(this);
